# Generated by Django 2.0.8 on 2018-10-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('user_rating', models.FloatField(default=0.0)),
                ('learning_credit', models.IntegerField(default=10)),
            ],
        ),
    ]
