# Generated by Django 2.0.8 on 2018-10-28 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrolled_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('ws_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('ws_name', models.CharField(max_length=200)),
                ('min_cap', models.IntegerField(null=True)),
                ('max_cap', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='ws_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Workshop'),
        ),
    ]
