# Generated by Django 2.0.8 on 2018-11-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181028_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='ws_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
