# Generated by Django 2.0.8 on 2018-12-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181114_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='location',
        ),
        migrations.AddField(
            model_name='workshop',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='state',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='street',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='zip',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
