# Generated by Django 2.0.8 on 2018-12-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181205_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
